<a href="https://colab.research.google.com/github/Robert-Dstech/Data-science-/blob/main/Feature_engineering_hypothesis_1(claim_within_15_days_of_expiry).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path='/content/drive/MyDrive/AutoInsClaims.csv'

In [ ]:
df=pd.read_csv(path)

In [ ]:
EXPIRY_days= pd.to_datetime(df["EXPIRY_DATE"])

In [ ]:
loss_event_time=pd.to_datetime(df["LOSS_EVENT_TIME"])

In [ ]:
days_from_loss=(loss_event_time-EXPIRY_days)

In [ ]:
CLEAN_DAYS=abs(days_from_loss)

In [ ]:
df['CLEANER']=CLEAN_DAYS

In [ ]:
df4=df.assign(CLEAN_DAYS=CLEAN_DAYS)

In [ ]:
df4

,HOUSEHOLD_ID,DRIVER_ID,POLICY_ID,CLAIM_ID,INCIDENT_CAUSE,DESCRIPTION,CLAIM_STATUS,ODOMETER_AT_LOSS,LOSS_EVENT_TIME,CLAIM_INIT_TIME,...,SSN,DRIVERS_LICENSE_ID,DRIVERS_LICENSE_EXPIRY,DRIVERS_LICENSE_STATE,DATE_AT_CURRENT_ADDRESS,CONTACT_NUMBER,EMAIL,COMMUTE_DISCOUNT,CLEANER,CLEAN_DAYS
0,CH42335,XZJ2837,NW5567882,A-2017-UU907,3,NaN,1,157654.9,4/25/17,4/28/17,...,457-20-9007,X151-5971-1594,8/19/18,IL,4/16/99,634-603-0960,wdorau@freshmaail.com,0,147 days 00:00:00,147 days
1,0,0,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,73 days
2,AF28736,UQM2512,RR8595908,A-2016-ZG694,1,NaN,1,83968.6,1/7/16,1/11/16,...,076-62-7083,V549-5272-3181,11/19/19,IL,5/21/05,723-552-0479,esebranek@zohoo.com,0,229 days 00:00:00,229 days
3,EF53594,YDT5591,RN5640634,A-2016-NG783,1,NaN,1,309570.3,12/11/16,12/18/16,...,571-32-3662,Z350-2956-6553,5/16/19,IL,3/11/00,741-637-0631,dnickless@life.com,0,140 days 00:00:00,140 days
4,0,0,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,150 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,CM11612,GJI9724,QY3512250,A-2016-TJ210,3,NaN,1,77438.7,11/29/16,12/1/16,...,037-94-2844,E550-8174-2772,6/23/18,IL,6/21/15,841-453-0442,mino@gmxx.com,0,141 days 00:00:00,141 days
971,0,0,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,25 days
972,BA79937,BLV8655,TU0769843,A-2016-MT971,1,NaN,1,192320.1,8/22/16,9/3/16,...,006-98-8737,J721-8375-9029,12/24/19,IL,1/14/14,738-442-0942,dsprosty@yahoot.com,1,2 days 00:00:00,2 days
973,0,0,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,87 days
974,0,0,0,0,0,0.0,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,177 days